---
- hosts: webservers

  gather_facts: False

  become: True
  become_user: www-data

  vars:
    release_dir: /var/www/{{ domain }}/releases/{{ timestamp.stdout }}

  tasks:

  - name: Get timestamp
    local_action: shell date +%s%3N
    register: timestamp
    run_once: True
    become: False

  - name: Create release directory
    file: path={{ release_dir }} state=directory

  - name: Upload and unpack files
    unarchive: src={{ archive }} dest={{ release_dir }}

  - name: Update app version
    file:
      state: link
      src: "{{ release_dir }}"
      path: /var/www/{{ domain }}/current
