---

- name: Install Memcached
  apt: name={{ item }} state=installed
  with_items:
    - memcached
    - libmemcached-dev

- name: Copy Memcached config
  template: src=memcached.conf.j2 dest=/etc/memcached.conf
  notify:
    - restart Memcached
