---
- hosts: webservers

  become: True

  tasks:

  - name: Install required system packages
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items:
      - python-dev
      - libpq-dev

  - name: Copy mime.types
    template: src=templates/mime.types.1.j2 dest=/etc/nginx/mime.types.1
    notify:
     - reload nginx

  - name: Copy nginx config
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
     - reload nginx

  - name: Copy nginx site config
    template: src=templates/{{ domain }}.j2 dest=/etc/nginx/sites-available/{{ domain }}
    notify:
     - reload nginx

  - name: Activate nginx site config
    file:
      state: link
      src: /etc/nginx/sites-available/{{ domain }}
      path: /etc/nginx/sites-enabled/{{ domain }}

  - name: Check nginx syntax of configuration files
    shell: "nginx -t"
    register: result
    changed_when: "result.rc != 0"
    always_run: yes

  # TODO ensure uWSGI log directories exist

  handlers:

  - name: reload nginx
    service: name=nginx state=reloaded
