---

- name: restart Memcached
  service: name=memcached state=restarted

- name: reload Nginx
  service: name=nginx state=reloaded

- name: restart uWSGI
  become_user: root
  service: name=uwsgi-{{ domain }} state=restarted
